[package]
name = "saturn"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Erik Hollensbe <erik+github@hollensbe.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "*"
notify-rust = "*"
anyhow = "*"
async-recursion = "*"
chrono = { version = "*", features = [ "serde" ] }
chrono-tz = "*"
rand = "*"
serde = "*"
serde_derive = "*"
ciborium = "*"
clap = { version = "*", features = [ "derive" ] }
regex = "*"
fancy-duration = { version = "*", default-features = false, features = [ "chrono" ] }
ttygrid = "*"
nix = "*"
serde_yaml = "*"
tokio = { version = "*", features = [ "full" ] }
gcal = { version = "*", path = "../gcal" }
davisjr = "*"
url = "*"
async-trait = "*"
reqwest = { version = "*", features = [ "json" ]}
uuid = { version = "*", features = [ "v4" ] }

[dev-dependencies]
tempfile = "*"
